<a href="https://colab.research.google.com/github/harshavardhanbatsala/Carvan/blob/main/Caravan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import warnings

warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np

from sklearn.pipeline import Pipeline,FeatureUnion
from sklearn.base import BaseEstimator, TransformerMixin


In [2]:
train_file=r'https://raw.githubusercontent.com/harshavardhanbatsala/Carvan/main/carvan_train.csv'
test_file=r'https://raw.githubusercontent.com/harshavardhanbatsala/Carvan/main/carvan_test.csv'

In [3]:
cd_train=pd.read_csv(train_file)
cd_test=pd.read_csv(test_file)

In [4]:
cd_train.head()

V1  V2  V3  V4  V5  V6  V7  V8  V9  V10  ...  V77  V78  V79  V80  V81  V82  \
0  33   1   3   2   8   0   5   1   3    7  ...    0    0    0    1    0    0   
1  37   1   2   2   8   1   4   1   4    6  ...    0    0    0    1    0    0   
2  37   1   2   2   8   0   4   2   4    3  ...    0    0    0    1    0    0   
3   9   1   3   3   3   2   3   2   4    5  ...    0    0    0    1    0    0   
4  40   1   4   2  10   1   4   1   4    7  ...    0    0    0    1    0    0   

   V83  V84  V85  V86  
0    0    0    0    0  
1    0    0    0    0  
2    0    0    0    0  
3    0    0    0    0  
4    0    0    0    0  

[5 rows x 86 columns]

In [5]:
cd_train.describe()

V1           V2           V3           V4           V5  \
count  5822.000000  5822.000000  5822.000000  5822.000000  5822.000000   
mean     24.253349     1.110615     2.678805     2.991240     5.773617   
std      12.846706     0.405842     0.789835     0.814589     2.856760   
min       1.000000     1.000000     1.000000     1.000000     1.000000   
25%      10.000000     1.000000     2.000000     2.000000     3.000000   
50%      30.000000     1.000000     3.000000     3.000000     7.000000   
75%      35.000000     1.000000     3.000000     3.000000     8.000000   
max      41.000000    10.000000     5.000000     6.000000    10.000000   

                V6           V7           V8           V9          V10  ...  \
count  5822.000000  5822.000000  5822.000000  5822.000000  5822.000000  ...   
mean      0.696496     4.626932     1.069907     3.258502     6.183442  ...   
std       1.003234     1.715843     1.017503     1.597647     1.909482  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     4.000000     0.000000     2.000000     5.000000  ...   
50%       0.000000     5.000000     1.000000     3.000000     6.000000  ...   
75%       1.000000     6.000000     2.000000     4.000000     7.000000  ...   
max       9.000000     9.000000     5.000000     9.000000     9.000000  ...   

               V77          V78          V79          V80          V81  \
count  5822.000000  5822.000000  5822.000000  5822.000000  5822.000000   
mean      0.005325     0.006527     0.004638     0.570079     0.000515   
std       0.072782     0.080532     0.077403     0.562058     0.022696   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     1.000000     0.000000   
75%       0.000000     0.000000     0.000000     1.000000     0.000000   
max       1.000000     1.000000     2.000000     7.000000     1.000000   

               V82          V83          V84          V85          V86  
count  5822.000000  5822.000000  5822.000000  5822.000000  5822.000000  
mean      0.006012     0.031776     0.007901     0.014256     0.059773  
std       0.081632     0.210986     0.090463     0.119996     0.237087  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       2.000000     3.000000     2.000000     2.000000     1.000000  

[8 rows x 86 columns]

In [6]:
cd_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5822 entries, 0 to 5821
Data columns (total 86 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   V1      5822 non-null   int64
 1   V2      5822 non-null   int64
 2   V3      5822 non-null   int64
 3   V4      5822 non-null   int64
 4   V5      5822 non-null   int64
 5   V6      5822 non-null   int64
 6   V7      5822 non-null   int64
 7   V8      5822 non-null   int64
 8   V9      5822 non-null   int64
 9   V10     5822 non-null   int64
 10  V11     5822 non-null   int64
 11  V12     5822 non-null   int64
 12  V13     5822 non-null   int64
 13  V14     5822 non-null   int64
 14  V15     5822 non-null   int64
 15  V16     5822 non-null   int64
 16  V17     5822 non-null   int64
 17  V18     5822 non-null   int64
 18  V19     5822 non-null   int64
 19  V20     5822 non-null   int64
 20  V21     5822 non-null   int64
 21  V22     5822 non-null   int64
 22  V23     5822 non-null   int64
 23  V24     5822 

In [7]:
cd_train.dtypes

V1     int64
V2     int64
V3     int64
V4     int64
V5     int64
       ...  
V82    int64
V83    int64
V84    int64
V85    int64
V86    int64
Length: 86, dtype: object

In [8]:
cd_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 85 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   V1      4000 non-null   int64
 1   V2      4000 non-null   int64
 2   V3      4000 non-null   int64
 3   V4      4000 non-null   int64
 4   V5      4000 non-null   int64
 5   V6      4000 non-null   int64
 6   V7      4000 non-null   int64
 7   V8      4000 non-null   int64
 8   V9      4000 non-null   int64
 9   V10     4000 non-null   int64
 10  V11     4000 non-null   int64
 11  V12     4000 non-null   int64
 12  V13     4000 non-null   int64
 13  V14     4000 non-null   int64
 14  V15     4000 non-null   int64
 15  V16     4000 non-null   int64
 16  V17     4000 non-null   int64
 17  V18     4000 non-null   int64
 18  V19     4000 non-null   int64
 19  V20     4000 non-null   int64
 20  V21     4000 non-null   int64
 21  V22     4000 non-null   int64
 22  V23     4000 non-null   int64
 23  V24     4000 

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [10]:
cd_train1,cd_train2=train_test_split(cd_train,train_size=0.8,random_state=27)

In [11]:
cd_train1.shape

(4657, 86)

In [12]:
cd_train2.shape

(1165, 86)

In [13]:
x_train1=cd_train1.drop('V86',axis=1)
y_train1=cd_train1['V86']

In [14]:
x_train2=cd_train2.drop('V86',axis=1)
y_train2=cd_train2['V86']

In [15]:
model=LogisticRegression(fit_intercept=True)

In [16]:
params={'class_weight':['balanced',None],
        'penalty':['l1','l2'],
        'C':np.linspace(0.0001,0.1,100)}

In [17]:
from sklearn.model_selection import GridSearchCV

In [18]:
grid_search=GridSearchCV(model,param_grid=params,cv=10,scoring="roc_auc")

In [19]:
grid_search.fit(x_train1,y_train1)

GridSearchCV(cv=10, estimator=LogisticRegression(),
             param_grid={'C': array([0.0001    , 0.00110909, 0.00211818, 0.00312727, 0.00413636,
       0.00514545, 0.00615455, 0.00716364, 0.00817273, 0.00918182,
       0.01019091, 0.0112    , 0.01220909, 0.01321818, 0.01422727,
       0.01523636, 0.01624545, 0.01725455, 0.01826364, 0.01927273,
       0.02028182, 0.02129091, 0.0223    , 0.02330909, 0.02431818,
       0.02532727, 0.0...
       0.07073636, 0.07174545, 0.07275455, 0.07376364, 0.07477273,
       0.07578182, 0.07679091, 0.0778    , 0.07880909, 0.07981818,
       0.08082727, 0.08183636, 0.08284545, 0.08385455, 0.08486364,
       0.08587273, 0.08688182, 0.08789091, 0.0889    , 0.08990909,
       0.09091818, 0.09192727, 0.09293636, 0.09394545, 0.09495455,
       0.09596364, 0.09697273, 0.09798182, 0.09899091, 0.1       ]),
                         'class_weight': ['balanced', None],
                         'penalty': ['l1', 'l2']},
             scoring='roc_auc')

In [20]:
grid_search.best_estimator_

LogisticRegression(C=0.020281818181818182)

In [21]:
logr=grid_search.best_estimator_

In [22]:
def report(results, n_top=3):
  for i in range(1, n_top + 1):
    candidates = np.flatnonzero(results['rank_test_score'] == i)
    for candidate in candidates:
      print("Model with rank: {0}".format(i))
      print("Mean validation score: {0:.3f} (std: {1:.3f})".format(
                  results['mean_test_score'][candidate],
                  results['std_test_score'][candidate]))
      print("Parameters: {0}".format(results['params'][candidate]))
      print("")

In [23]:
report(grid_search.cv_results_,5)

Model with rank: 1
Mean validation score: 0.734 (std: 0.050)
Parameters: {'C': 0.020281818181818182, 'class_weight': None, 'penalty': 'l2'}

Model with rank: 2
Mean validation score: 0.732 (std: 0.053)
Parameters: {'C': 0.04046363636363637, 'class_weight': None, 'penalty': 'l2'}

Model with rank: 3
Mean validation score: 0.732 (std: 0.052)
Parameters: {'C': 0.03642727272727273, 'class_weight': None, 'penalty': 'l2'}

Model with rank: 4
Mean validation score: 0.732 (std: 0.051)
Parameters: {'C': 0.027345454545454544, 'class_weight': None, 'penalty': 'l2'}

Model with rank: 5
Mean validation score: 0.732 (std: 0.052)
Parameters: {'C': 0.032390909090909095, 'class_weight': None, 'penalty': 'l2'}



In [24]:
logr.fit(x_train1,y_train1)

LogisticRegression(C=0.020281818181818182)

In [25]:
train_score=logr.predict_proba(x_train1)

In [26]:
train_score

array([[0.75338243, 0.24661757],
       [0.972643  , 0.027357  ],
       [0.98768585, 0.01231415],
       ...,
       [0.96953285, 0.03046715],
       [0.94995958, 0.05004042],
       [0.87437171, 0.12562829]])

In [27]:
train2_score=logr.predict_proba(x_train2)[:,1]

In [28]:
train2_score

array([0.16796014, 0.02902048, 0.0710285 , ..., 0.03732401, 0.06268724,
       0.08385139])

In [29]:
pd.DataFrame(train2_score,y_train2).to_csv("mysubmission.csv",index=False)

In [30]:
cutoffs=np.linspace(0.01,0.99,99)
cutoffs

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99])

In [31]:
train_score=logr.predict_proba(x_train1)[:,1]

In [32]:
real=y_train1

In [33]:
print(logr.classes_)

[0 1]


In [34]:
from sklearn.metrics import fbeta_score

In [35]:
KS_all=[]

for cutoff in cutoffs:
    predicted=(train_score>cutoff).astype(int)
    TP=((predicted==1) & (real==1)).sum()
    TN=((predicted==0) & (real==0)).sum()
    FP=((predicted==1) & (real==0)).sum()
    FN=((predicted==0) & (real==1)).sum()
    P=TP+FN
    N=TN+FP
    KS=(TP/P)-(FP/N)
    KS_all.append(KS)

In [36]:
list(zip(cutoffs,KS_all))

[(0.01, 0.06631069980073057),
 (0.02, 0.21226939520017807),
 (0.03, 0.2942375612176228),
 (0.04, 0.3456153363755893),
 (0.05, 0.3905442821798796),
 (0.060000000000000005, 0.40895991852386726),
 (0.06999999999999999, 0.40193391198416323),
 (0.08, 0.40369246034669926),
 (0.09, 0.3999690534785364),
 (0.09999999999999999, 0.3662185151891749),
 (0.11, 0.3322395620985344),
 (0.12, 0.2902660909631245),
 (0.13, 0.28139393611917524),
 (0.14, 0.25925653028911255),
 (0.15000000000000002, 0.22949383607512963),
 (0.16, 0.2174238740132726),
 (0.17, 0.20147086032967051),
 (0.18000000000000002, 0.19330114240148283),
 (0.19, 0.1828472764605039),
 (0.2, 0.1704080847377978),
 (0.21000000000000002, 0.13867725725401198),
 (0.22, 0.11724228833971094),
 (0.23, 0.10183370420037627),
 (0.24000000000000002, 0.10388943741188839),
 (0.25, 0.08466820908059358),
 (0.26, 0.07238702472938167),
 (0.27, 0.06727429915953177),
 (0.28, 0.06841637316592739),
 (0.29000000000000004, 0.04782465602695786),
 (0.3, 0.02479078350

In [37]:
mycutoff=cutoffs[KS_all==max(KS_all)][0]

In [38]:
mycutoff

0.060000000000000005

In [40]:
y_train2.unique()

array([1, 0])

In [41]:
from sklearn.model_selection import RandomizedSearchCV

In [42]:
params={ 'class_weight':[None,'balanced'],
        'criterion':['entropy','gini'],
        'max_depth':[None,2,4,5],
            'min_samples_leaf':[1,2,5,10,15,20],
            'min_samples_split':[2,5,10,15,20]
       }

In [43]:
from sklearn.tree import DecisionTreeClassifier
clf=DecisionTreeClassifier()

In [44]:
random_search=RandomizedSearchCV(clf,
                                 cv=10,
                                 param_distributions=params,
                                 scoring='roc_auc',
                                 n_iter=100, # number of random iterations out of total iterations
                                 n_jobs=-1,verbose=20
                                    )

In [45]:
random_search.fit(x_train1,y_train1)

Fitting 10 folds for each of 100 candidates, totalling 1000 fits


RandomizedSearchCV(cv=10, estimator=DecisionTreeClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'class_weight': [None, 'balanced'],
                                        'criterion': ['entropy', 'gini'],
                                        'max_depth': [None, 2, 4, 5],
                                        'min_samples_leaf': [1, 2, 5, 10, 15,
                                                             20],
                                        'min_samples_split': [2, 5, 10, 15,
                                                              20]},
                   scoring='roc_auc', verbose=20)

In [46]:
random_search.best_estimator_

DecisionTreeClassifier(class_weight='balanced', max_depth=4,
                       min_samples_leaf=20, min_samples_split=15)

In [47]:
report(random_search.cv_results_,5)

Model with rank: 1
Mean validation score: 0.738 (std: 0.036)
Parameters: {'min_samples_split': 15, 'min_samples_leaf': 20, 'max_depth': 4, 'criterion': 'gini', 'class_weight': 'balanced'}

Model with rank: 2
Mean validation score: 0.734 (std: 0.046)
Parameters: {'min_samples_split': 20, 'min_samples_leaf': 1, 'max_depth': 4, 'criterion': 'entropy', 'class_weight': None}

Model with rank: 3
Mean validation score: 0.733 (std: 0.028)
Parameters: {'min_samples_split': 10, 'min_samples_leaf': 15, 'max_depth': 4, 'criterion': 'entropy', 'class_weight': 'balanced'}

Model with rank: 4
Mean validation score: 0.732 (std: 0.039)
Parameters: {'min_samples_split': 20, 'min_samples_leaf': 15, 'max_depth': 4, 'criterion': 'gini', 'class_weight': 'balanced'}

Model with rank: 5
Mean validation score: 0.731 (std: 0.046)
Parameters: {'min_samples_split': 10, 'min_samples_leaf': 2, 'max_depth': 4, 'criterion': 'entropy', 'class_weight': None}



In [49]:
dtree=DecisionTreeClassifier(**{'min_samples_split': 15, 'min_samples_leaf': 20, 'max_depth': 4, 'criterion': 'gini', 'class_weight': 'balanced'})

In [50]:
dtree.fit(x_train1,y_train1)

DecisionTreeClassifier(class_weight='balanced', max_depth=4,
                       min_samples_leaf=20, min_samples_split=15)

In [51]:
import os
os.getcwd()

'/content'

In [55]:
%matplotlib inline
from sklearn import tree

In [56]:
dotfile = open("mytree.dot", 'w')

tree.export_graphviz(dtree,out_file=dotfile,
                     feature_names=x_train1.columns,
                    class_names=["0","1"],
                     )
dotfile.close()

In [57]:
x_train1.shape

(4657, 85)

In [60]:
predict_tree=dtree.predict(x_train2)

In [59]:
y_train2

1676    1
2550    0
5572    0
792     0
3012    0
       ..
4518    0
1916    0
1363    0
4254    0
2645    0
Name: V86, Length: 1165, dtype: int64